export const thisConstants = {

    ColumnDefs: {
        ActivityLog: [
            { headerName: 'Seq No', field: 'mrSeqNmbr', width: 70, hide: false, suppressFilter: true },
            { headerName: 'Rcrd Ind', field: 'mrRcrdIndctr', width: 60, hide: false, suppressFilter: true, headerClass: 'cell-wrap-text' },
            { headerName: 'Buy Sell', field: 'mrBuySellFlag', width: 60, hide: false, suppressFilter: true },
            { headerName: 'Acty Type', field: 'mrActivityType', width: 60, hide: false, suppressFilter: true },
            { headerName: 'Trade No', field: 'mrFillNmbr', width: 110, hide: false, suppressFilter: true },
            { headerName: 'Trade Qty', field: 'mrFillQty', width:70, hide: false, suppressFilter: true },
            { headerName: 'Trade Price', field: 'mrFillPrice', width: 70, hide: false, suppressFilter: true },
            { headerName: 'Trade Amt', field: 'mrFillAmnt', width: 70, hide: false, suppressFilter: true },
            { headerName: 'Txn Time', field: 'mrJiffyTmst', width: 70, hide: true, suppressFilter: true },
            { headerName: 'Liquidity Ind', field: 'mrLiquidityFlag', width: 90, hide: false, suppressFilter: true },
            { headerName: 'First Trade After Flex', field: 'mrFirstTradeAfterFlex', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Rcrd Time', field: 'mrRecordTimeString', width: 80, hide: false, suppressFilter: true },
            { headerName: 'Mkt Type', field: 'mrMktType', width: 60, hide: false, suppressFilter: true },
            { headerName: 'Buy Order No', field: 'mrBuyOrderNmbr', width: 130, hide: false, suppressFilter: true },
            { headerName: 'Buy Broker', field: 'mrBuyBrokerId', width: 90, hide: false, suppressFilter: true },
            { headerName: 'Buy Acct', field: 'mrBuyClientId', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Buy Pro Cli', field: 'mrBuyProClientFlag', width: 100, hide: true, suppressFilter: true },
            { headerName: 'Buy Dealer', field: 'mrBuyDealerId', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Buy NNF Id', field: 'mrBuyNnfId', width: 130, hide: false, suppressFilter: true },
            { headerName: 'Buy CP Code', field: 'mrBuyCpCode', width: 100, hide: true, suppressFilter: true },
            { headerName: 'Buy Orig Qty', field: 'mrBuyOrderQty', width: 80, hide: false, suppressFilter: true },
            { headerName: 'Buy Rmng Qty', field: 'mrBuyRmngQty', width: 80, hide: false, suppressFilter: true },
            { headerName: 'Buy Disc Qy', field: 'mrBuyDisclQty', width: 80, hide: false, suppressFilter: true },
            { headerName: 'Buy Rmng Disc Qty', field: 'mrBuyRmngDisclQty', width: 80, hide: false, suppressFilter: true },
            { headerName: 'Buy Limit Price', field: 'mrBuyLimitPrice', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Buy Trig Price', field: 'mrBuyTriggerPrice', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Buy Entry Tmst', field: 'mrBuyEntryTmstString', width: 130, hide: false, suppressFilter: true },
            { headerName: 'Buy Last Mod Tmst', field: 'mrBuyLastModTmstString', width: 130, hide: false, suppressFilter: true },
            { headerName: 'Buy Book Type', field: 'mrBuyBookType', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Buy Mkt Flag', field: 'mrBuyMktFlag', width: 85, hide: true, suppressFilter: true },
            { headerName: 'Buy OnStop Flag', field: 'mrBuyOnStopFlag', width: 90, hide: true, suppressFilter: true },
            { headerName: 'Buy Day Flag', field: 'mrBuyDayFlag', width: 90, hide: true, suppressFilter: true },
            { headerName: 'Buy FOK Flag', field: 'mrBuyFokFlag', width: 90, hide: true, suppressFilter: true },
            { headerName: 'Buy TPP Flag', field: 'mrBuyTtpFlag', width: 90, hide: true, suppressFilter: true },
            { headerName: 'Buy STP Flag', field: 'mrBuyStpFlag', width: 90, hide: true, suppressFilter: true },
            { headerName: 'Buy STP Cxl Flag', field: 'mrBuyStpClxFlag', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Buy ALGO Flag', field: 'mrBuyAlgoInd', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Buy PAN', field: 'mrBuyPan', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Buy ALGO Id', field: 'mrBuyAlgoId', width: 100, hide: true, suppressFilter: true },
            { headerName: 'Buy ALGO Catg', field: 'mrBuyAlgoCategory', width: 100, hide: true, suppressFilter: true },
            { headerName: 'Buy ATO Flag', field: 'mrBuyAtoFlag', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Buy Colo Flag', field: 'mrBuyColoFlag', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Sell Order No', field: 'mrSellOrderNmbr', width: 130, hide: false, suppressFilter: true },
            { headerName: 'Sell Broker', field: 'mrSellBrokerId', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Sell Acct', field: 'mrSellClientId', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Sell Pro Cli', field: 'mrSellProClientFlag', width: 100, hide: true, suppressFilter: true },
            { headerName: 'Sell Dealer', field: 'mrSellDealerId', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Sell NNF Id', field: 'mrSellNnfId', width: 130, hide: false, suppressFilter: true },
            { headerName: 'Sell CP Code', field: 'mrSellCpCode', width: 90, hide: true, suppressFilter: true },
            { headerName: 'Sell Orig Qty', field: 'mrSellOrderQty', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Sell Rmng Qty', field: 'mrSellRmngQty', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Sell Disc Qty', field: 'mrSellDisclQty', width: 80, hide: false, suppressFilter: true },
            { headerName: 'Sell Rmng Disc Qty', field: 'mrSellRmngDisclQty', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Sell Limit Price', field: 'mrSellLimitPrice', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Sell Trig Price', field: 'mrSellTriggerPrice', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Sell Entry Tmst', field: 'mrSellEntryTmstString', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Sell Last Mod Tmst', field: 'mrSellLastModTmstString', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Sell Book Type', field: 'mrSellBookType', width: 85, hide: false, suppressFilter: true },
            { headerName: 'Sell Mkt Flag', field: 'mrSellMktFlag', width: 85, hide: false, suppressFilter: true },
            { headerName: 'Sell OnStop Flag', field: 'mrSellOnStopFlag', width: 100, hide: true, suppressFilter: true },
            { headerName: 'Sell Day Flag', field: 'mrSellDayFlag', width: 90, hide: true, suppressFilter: true },
            { headerName: 'Sell FOK Flag', field: 'mrSellFokFlag', width: 90, hide: true, suppressFilter: true },
            { headerName: 'Sell TPP Flag', field: 'mrSellTtpFlag', width: 90, hide: true, suppressFilter: true },
            { headerName: 'Sell STP Flag', field: 'mrSellStpFlag', width: 90, hide: true, suppressFilter: true },
            { headerName: 'Sell STP Cxl Flag', field: 'mrSellStpClxFlag', width: 90, hide: false, suppressFilter: true },
            { headerName: 'Sell ALGO Flag', field: 'mrSellAlgoInd', width: 90, hide: false, suppressFilter: true },
            { headerName: 'Sell PAN', field: 'mrSellPan', width: 100, hide: false, suppressFilter: true },
            { headerName: 'Sell ALGO Id', field: 'mrSellAlgoId', width: 100, hide: true, suppressFilter: true },
            { headerName: 'Sell ALGO Catg', field: 'mrSellAlgoCategory', width: 100, hide: true, suppressFilter: true },
            { headerName: 'Sell ATO Flag', field: 'mrSellAtoFlag', width: 90, hide: false, suppressFilter: true },
            { headerName: 'Sell Colo Flag', field: 'mrSellColoFlag', width: 80, hide: false, suppressFilter: true },
        ],
        BuyOrderLog: [
            { headerName: 'Price', field: 'dummyPrice', width: 80 },
            { headerName: 'Qty', field: 'qty', width: 60 },
            { headerName: 'Order', field: 'order', width: 80 }
        ],
        SellOrderLog: [
            { headerName: 'Price', field: 'dummyPrice', width: 80 },
            { headerName: 'Qty', field: 'qty', width: 60 },
            { headerName: 'Order', field: 'order', width: 80 }
        ],
        AwayLTP: [
            { headerName: '', field: 'rowText', width: 60 },
            { headerName: 'Buy Qty', field: 'buyAwayQty', width: 70 },
            { headerName: 'Sell Qty', field: 'sellAwayQty', width: 70 }
        ],
        EventLog: [
            { headerName: 'Time', field: 'mrEventTime', width: 60, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'Event', field: 'mrEvent', width: 80, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'Description', field: 'mrEventDescription', width: 130, autoHeight: true, cellClass: 'cell-wrap-text' }
        ],
        OrderBook: [
            { headerName: 'Seq Nmbr', field: 'mrSeqNmbr', width: 85, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'RecordTime', field: 'mrRecordTimeString', width: 85, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'Order Nmbr', field: 'mrBuyOrderNmbr', width: 85, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'Broker', field: 'mrBuyBrokerId', width: 85, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'Client', field: 'mrBuyClientId', width: 85, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'Pro/Cli', field: 'mrBuyProClientFlag', width: 75, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'Dealer', field: 'mrBuyDealerId', width: 85, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'NNF', field: 'mrBuyNnfId', width: 85, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'Order Qty', field: 'mrBuyOrderQty', width: 85, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'Rmng Qty', field: 'mrBuyRmngQty', width: 85, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'Discl Qty', field: 'mrBuyDisclQty', width: 85, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'Rmng Discl Qty', field: 'mrBuyRmngDisclQty', width: 85, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'Limit Price', field: 'mrBuyLimitPrice', width: 85, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'Trig Price', field: 'mrBuyTriggerPrice', width: 85, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'Algo Ind', field: 'mrBuyAlgoInd', width: 75, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'PAN', field: 'mrBuyPan', width: 85, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'ATO Flag', field: 'mrBuyAtoFlag', width: 75, autoHeight: true, cellClass: 'cell-wrap-text' },
            { headerName: 'Colo Flag', field: 'mrBuyColoFlag', width: 75, autoHeight: true, cellClass: 'cell-wrap-text' }
        ],
        
    },

    patterns: {
        pan: '^([A-Za-z]{5})([0-9]{4})([A-Za-z]{1})+$',
        numeric: '^[0-9]+$',
        decimal: '^([0-9]{0,2})+(.[0-9]{0,2})?$',
        alphanumeric: '^([A-Za-z0-9])+$',
        time:'^(2[0-3]|[01]?[0-9]):([0-5]?[0-9]):([0-5]?[0-9])$',
        alpabets:'^[a-zA-Z ]*$'
    }
}
